// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef linsim_ui_h
#define linsim_ui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *linsim_window;
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Button.H>
extern Fl_Button *btn_select_input;
#include <FL/Fl_Output.H>
extern Fl_Output *txt_input_file;
extern Fl_Button *btn_select_output;
extern Fl_Output *txt_output_file;
extern Fl_Button *btn_select_simulation;
#include <FL/Fl_Input.H>
extern Fl_Input *txt_simulation;
extern Fl_Output *txt_simulations_filename;
#include <FL/Fl_Group.H>
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *p0_on;
#include <FL/Fl_Float_Input.H>
extern Fl_Float_Input *inp_spread0;
extern Fl_Float_Input *inp_offset0;
extern Fl_Check_Button *p1_on;
extern Fl_Float_Input *inp_delay1;
extern Fl_Float_Input *inp_spread1;
extern Fl_Float_Input *inp_offset1;
extern Fl_Check_Button *p2_on;
extern Fl_Float_Input *inp_delay2;
extern Fl_Float_Input *inp_spread2;
extern Fl_Float_Input *inp_offset2;
extern Fl_Check_Button *inp_AWGN_on;
extern Fl_Float_Input *inp_AWGN_rms;
#include <FL/Fl_Progress.H>
extern Fl_Progress *progress;
extern Fl_Button *btn_test;
extern Fl_Button *btn_abort;
extern Fl_Group *lbl_batch;
Fl_Double_Window* make_linsim_window();
extern Fl_Menu_Item menu_[];
#define mnu_open_simulation_set (menu_+1)
#define mnu_save_simulation_set (menu_+2)
#define mnu_save_simulation_set_as (menu_+3)
#define mnuAddSimulation (menu_+7)
#define mnuBatchProcess (menu_+8)
#define mnuAWGNseries (menu_+9)
#define mnu_choose_folder (menu_+10)
#define mnu_sr_as_input (menu_+13)
#define mnu_sr_8000 (menu_+14)
#define mnu_sr_11025 (menu_+15)
#define mnu_sr_16000 (menu_+16)
#define mnu_sr_22050 (menu_+17)
#define mnu_sr_24000 (menu_+18)
#define mnu_sr_44100 (menu_+19)
#define mnu_sr_48000 (menu_+20)
extern Fl_Menu_Item menu_1[];
#include <FL/Fl_Check_Browser.H>
extern Fl_Check_Browser *tbl_batch_simulations;
extern Fl_Button *btn_cancel_batch;
extern Fl_Button *btn_clear_batch_selections;
extern Fl_Button *btn_all_batch;
#include <FL/Fl_Return_Button.H>
extern Fl_Return_Button *btn_batch_process;
Fl_Double_Window* make_batch_selector_dialog();
extern Fl_Return_Button *btn_select;
#include <FL/Fl_Browser.H>
extern Fl_Browser *tbl_simulations;
extern Fl_Button *btn_delete_selection;
extern Fl_Button *btn_update_selection;
Fl_Double_Window* make_selector_dialog();
#include <FL/Fl_Spinner.H>
extern Fl_Spinner *cntr_Low_dB;
extern Fl_Spinner *cntr_High_dB;
extern Fl_Spinner *cntr_Step_dB;
extern Fl_Return_Button *btn_AWGNseries_process;
extern Fl_Button *btn_cancel_AWGNseries;
Fl_Double_Window* make_AWGNseries_dialog();
#include <FL/Fl_File_Input.H>
extern Fl_File_Input *finp_output_wav_folder;
extern Fl_Check_Button *btn_same_as_input_file;
Fl_Double_Window* make_folder_dialog();
#endif
